name: Hockey Aces
favicon: null
layout_spectrum: 0.2695787569973618
typography_spectrum: 0.74552
title: Hockey Aces
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdb827'
    - '#000000'
    - '#342a7a'
    - '#fee7b7'
    - '#795812'
  brandStrength: 0.8194283070042729
  lightness: 0.44127045245841146
  saturation: 0.3040877424646169
  rhythmicContrast: 0.6323893673252314
purpose: []
